## File generated by the BNF Converter (bnfc 2.9.4).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestTinyPlus

# Rules for building the parser.

AbsTinyPlus.hs LexTinyPlus.x ParTinyPlus.y PrintTinyPlus.hs TestTinyPlus.hs : TinyPlus.cf
	bnfc --haskell TinyPlus.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestTinyPlus : AbsTinyPlus.hs LexTinyPlus.hs ParTinyPlus.hs PrintTinyPlus.hs TestTinyPlus.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsTinyPlus.hs AbsTinyPlus.hs.bak ComposOp.hs ComposOp.hs.bak DocTinyPlus.txt DocTinyPlus.txt.bak ErrM.hs ErrM.hs.bak LayoutTinyPlus.hs LayoutTinyPlus.hs.bak LexTinyPlus.x LexTinyPlus.x.bak ParTinyPlus.y ParTinyPlus.y.bak PrintTinyPlus.hs PrintTinyPlus.hs.bak SkelTinyPlus.hs SkelTinyPlus.hs.bak TestTinyPlus.hs TestTinyPlus.hs.bak XMLTinyPlus.hs XMLTinyPlus.hs.bak ASTTinyPlus.agda ASTTinyPlus.agda.bak ParserTinyPlus.agda ParserTinyPlus.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak TinyPlus.dtd TinyPlus.dtd.bak TestTinyPlus LexTinyPlus.hs ParTinyPlus.hs ParTinyPlus.info ParDataTinyPlus.hs Makefile


# EOF
