## File generated by the BNF Converter (bnfc 2.9.4).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestMojeLatte

# Rules for building the parser.

AbsMojeLatte.hs LexMojeLatte.x ParMojeLatte.y PrintMojeLatte.hs TestMojeLatte.hs : mojeLatte.cf
	bnfc --haskell mojeLatte.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestMojeLatte : AbsMojeLatte.hs LexMojeLatte.hs ParMojeLatte.hs PrintMojeLatte.hs TestMojeLatte.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsMojeLatte.hs AbsMojeLatte.hs.bak ComposOp.hs ComposOp.hs.bak DocMojeLatte.txt DocMojeLatte.txt.bak ErrM.hs ErrM.hs.bak LayoutMojeLatte.hs LayoutMojeLatte.hs.bak LexMojeLatte.x LexMojeLatte.x.bak ParMojeLatte.y ParMojeLatte.y.bak PrintMojeLatte.hs PrintMojeLatte.hs.bak SkelMojeLatte.hs SkelMojeLatte.hs.bak TestMojeLatte.hs TestMojeLatte.hs.bak XMLMojeLatte.hs XMLMojeLatte.hs.bak ASTMojeLatte.agda ASTMojeLatte.agda.bak ParserMojeLatte.agda ParserMojeLatte.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak mojeLatte.dtd mojeLatte.dtd.bak TestMojeLatte LexMojeLatte.hs ParMojeLatte.hs ParMojeLatte.info ParDataMojeLatte.hs Makefile


# EOF
